feat(csv): when importing nulls do not treat them as string values
Apps72/DbMocker pull request #38
Opened 2024-12-16 14:40 UTC by zewa666

Hi there, I wonder whether this would be a good addition, since most of the times you're really looking for the null type vs a string with value null. Its not pure csv semantic though hence I'm unsure how you feel about this one.

2024-12-16 15:47 UTC, dvoituron commented
I think this could be a good idea, but `NULL` would have to be managed only using an option.

```csharp
public enum CsvImportOptions
{
    None = 0,
    RemoveEmptyLines = 1,
    TrimLines = 2,
    AllowNullString = 4,    // 👈 New option
}
```

2024-12-16 15:51 UTC, zewa666 commented
thats great. so by default it would be backwards compatible and treat it as a string.

one more idea I had is to allow to pass in the column type as 2nd row, so that the type doesnt have to be guessed but that wouldnt work well as an options enum, or would you simply pass in multiple enum values than?

2024-12-16 15:54 UTC, dvoituron commented
> one more idea I had (another future PR) is to allow to pass in the column type as 2nd row, so that the type doesnt have to be guessed but that wouldnt work well as an options enum, or would you simply pass in multiple enum values than?

It could also be an enum option to inform the code that the second line is a string representation of the type (`Int32`, `Int34`, `DateTime`, ...)

2025-01-09 22:24 UTC, dvoituron requested changes

2025-01-09 22:24 UTC, dvoituron commented on DbMocker.Tests/DbMockTableTests.cs
> +            MockTable table = MockTable.Empty().AddColumns("Col1").AddRow(11);
Can you avoid to reformat the existing code? This generates a PR that becomes very difficult to compare.

2025-01-10 04:40 UTC, zewa666 commented on DbMocker.Tests/DbMockTableTests.cs
> +            MockTable table = MockTable.Empty().AddColumns("Col1").AddRow(11);
sorry, CSharpier kicking in. Will fix that

2025-10-05 15:36 UTC, closed without merging